# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20171023_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='published_at',
            field=models.DateTimeField(null=True, verbose_name='datetime published'),
        ),
    ]
