# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20171023_0448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='choice',
            new_name='answer',
        ),
    ]
