# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20171023_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_published',
        ),
        migrations.AlterField(
            model_name='question',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='datetime published'),
        ),
    ]
